/*
 * Skills
 */

export const skills = [
  {
    skill: "Swift",
    subheading: "iOS Applications",
    color: "#16a34a",
    url: "https://apps.apple.com/us/developer/gavin-shrader/id1319656496",
    urlName: "View My Apps",
    urlOpensInNewTab: true,
    urlIsNavLink: false,
    urlIsHashLink: false,
    moreInfo: "I taught myself how to build iOS applications through the Swift programming language. I have published several applications to the app store.",
  },
  {
    skill: "HTML5",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects#maze-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I learned HTML in order to structure the content of websites.",
  },
  {
    skill: "CSS3",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects#maze-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I learned CSS in order to style and design the content of websites.",
  },
  {
    skill: "JavaScript",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects#maze-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I learned JavaScript in order to build interactivity into websites.",
  },
  {
    skill: "React",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects#react-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I learned the React framework in order to facilitate more complex and modern web apps.",
  },
  {
    skill: "ThreeJS",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects#threejs-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I am learning ThreeJS in order to build 3D graphics that run in a browser and eventually build a 3D game.",
  },
  {
    skill: "PHP",
    subheading: "Server-Side/Back-End",
    color: "#c026d3",
    url: "/projects#database-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I am capable of using PHP for basic server-side scripting such as an email contact form, user login/sign up, and a basic Blog.",
  },
  {
    skill: "MySQL",
    subheading: "Server-Side/Back-End",
    color: "#c026d3",
    url: "/projects#database-project",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    urlIsHashLink: true,
    moreInfo: "I am capable of using MySQL to setup database systems for a basic back-end.",
  },
  {
    skill: "Git/GitHub",
    subheading: "Version Control",
    color: "#e11d48",
    url: "https://github.com/gshrdr/",
    urlName: "GitHub Profile",
    urlOpensInNewTab: true,
    urlIsNavLink: false,
    urlIsHashLink: false,
    moreInfo: "I use Git for version control and I use GitHub to store my Git repositories on the cloud to showcase my projects.",
  },
  {
    skill: "Python",
    color: "#ea580c",
    url: "https://github.com/gshrdr/Learning-Python",
    urlName: "Python Interactive Demo",
    urlOpensInNewTab: true,
    urlIsNavLink: false,
    urlIsHashLink: false,
    moreInfo: "I have a junior level understanding of Python. I have used this to build simple GUIs and algorithms, and I can setup and navigate a Python development environment on both MacOS & Windows.",
  },
  {
    skill: "Technical Writing & Communication",
    color: "#ea580c",
    url: "/blog",
    urlName: "View Blog",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    urlIsHashLink: false,
    moreInfo: "I am capable of breaking down complex technical problems into simple steps & tutorials. You can view my technical writing on my Blog.",
  },
];
