/*
 * Skills
 */

export const skills = [
  {
    skill: "Swift",
    subheading: "iOS Applications",
    color: "#16a34a",
    url: "https://apps.apple.com/us/developer/gavin-shrader/id1319656496",
    urlName: "View My Apps",
    urlOpensInNewTab: true,
    urlIsNavLink: false,
    moreInfo: "I taught myself how to build iOS applications through the Swift programming language. I have published several applications to the app store.",
  },
  {
    skill: "HTML5",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    moreInfo: "I learned HTML in order to structure the content of websites.",
  },
  {
    skill: "CSS3",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    moreInfo: "I learned CSS in order to style and design the content of websites.",
  },
  {
    skill: "JavaScript",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    moreInfo: "I learned JavaScript in order to build interactivity into websites.",
  },
  {
    skill: "ReactJS",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    moreInfo: "I learned the React framework in order to facilitate more complex and modern web apps.",
  },
  {
    skill: "ThreeJS",
    subheading: "Web Development",
    color: "#2563eb",
    url: "/projects",
    urlName: "View Demo Project",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    moreInfo: "I am learning ThreeJS in order to build 3D graphics that run in a browser and eventually build a 3D game.",
  },
  {
    skill: "Git/GitHub",
    subheading: "Version Control",
    color: "#e11d48",
    url: "https://github.com/gshrdr/",
    urlName: "GitHub Profile",
    urlOpensInNewTab: true,
    urlIsNavLink: false,
    moreInfo: "I use Git for version control and I use GitHub to store my Git repositories on the cloud to showcase my projects.",
  },
  {
    skill: "Python",
    color: "#ea580c",
    url: null,
    urlName: null,
    urlOpensInNewTab: false,
    urlIsNavLink: false,
    moreInfo: "I have a junior level understanding of Python. I have used this to build simple GUIs and algorithms. I can setup and navigate a Python development environment and I have experience with several major Python libraries such as PyGame, PyQT, and NumPy.",
  },
  {
    skill: "Technical Writing & Communication",
    color: "#ea580c",
    url: "/blog",
    urlName: "View Blog",
    urlOpensInNewTab: false,
    urlIsNavLink: true,
    moreInfo: "I am capable of breaking down complex technical problems into simple steps & tutorials. My blog will showcase this in the near future with technical articles.",
  },
];
